Fixed string concat bug in example.
Without this patch the following error occurs:

$ python l2capserver.py
server_sock <bluetooth.bluez.BluetoothSocket object at 0xb6714690>
Accepted connection from ('9C:B6:D0:FC:B4:D2', 4097)
Data received: b'hello it is me'
Traceback (most recent call last):
  File "l2capserver.py", line 31, in <module>
    client_sock.send("Echo =>", str(data))
  File "<string>", line 3, in send
TypeError: an integer is required (got type str)